### ISSUE TITLE
Initial Issue

### ISSUE THREAD

**Issue by assassins719** [alessiocancian/react-native-side-menu#1] opened 2021-01-29 01:39 UTC
When the app starts the screen, the menu has appeared and after a few moments, it disappears.
How to fix and what is the problem?
I already set the isOpen={false}

**Comment by alessiocancian** [comment] 2021-02-16 08:18
Hi @assassins719 I've never seen something like that, could you please provide a reproducible sample code?

**Comment by assassins719** [comment] 2021-02-16 12:10
Here is my code
===========
constructor(props) {
    super(props);
    this.state = {
      open: false,
    }
}
-------
 <SideMenu
          isOpen={this.state.open}
          menu={this.drawerContent()}
          openMenuOffset={230}
          edgeHitWidth={100}
          toleranceX={150}
          toleranceY={100}
          overlayColor="rgba(0,0,0,0.3)"
          allowOverlayPressPropagation={true}
          onChange={val => {
            this.setState({open: val});
          }}>
        <View></View>
</SideMenu>

**Comment by alessiocancian** [comment] 2021-02-16 23:23
The view you use as children has a background color or is transparent?
You need to set a background color because the Side-Menu is rendered behind the page.

If it already has a background color try setting it's height to 100%

**Comment by alessiocancian** [comment] 2021-03-07 21:29
Closing the issue, fell free to reopen if setting a background color (as already stated in the README) doesn't fix your problem

**Closed by alessiocancian** 2021-03-07 21:29 UTC
